### ISSUE TITLE
Adding file-upload 

### ISSUE THREAD

**Issue by krishnaff** [meteoric/autoform-ionic#11]
Hello, 

I'm trying to add file upload capability using cfs:autoform. Unfortunately, the moment meteoric:autoform-ionic package is added to the project, the file upload input button breaks. 
Atleast It doesn't show up with the following lines of code:

```
  {{#autoForm id="insertForm" type="insert" collection="Docs"}}
  {{> afQuickField name="name"}}
  {{> afQuickField name="fileId" type="cfs-file" collection="files"}}
  <button type="submit">Submit</button>
  {{/autoForm}}
```

So the afQuickField does not generate an input type="file" tag at all in the HTML structure. Anyone else facing this weird issue? I made sure all dependencies for both packages are added to the project. 

I just began exploring meteoric, forgive me if i'm doing something obviously wrong. But any light on this would be greatly appreciated, thanks.

**Comment by nickw** [comment]
Ionic doesn't have a component for file uploads since you typically can't use them on mobile devices.

**Comment by krishnaff** [comment]
ok cool. Thanks @nickw

**Comment by krishnaff** [comment]
@nickw 
Hi Nick,
Any pointers on how to go about adding an avatar-upload field to the ionic-autoform?
Earlier I asked about file-upload, but I should have been more specific. 

Ideally something like the circular avatars in the meteoric-contacts demo app.
First we show an empty image-placeholder, clicking on which opens the device camera to capture a photo. Then we show a preview of the avatar image added.

I was able to do this **without** using meteoric/ionic (by using the standard cordova-camera plugin) 
But just couldn't figure out how to integrate that into the ionic-autoform. 
Thanks.

**Comment by nickw** [comment]
From an autoform perspective you'd probably just want to make the imageURL attribute a hidden field, and then populate it manually after a user uploads an image. The rest of it should be pretty standard. I have an ionic fork of the `camera` package if you're interested: https://github.com/meteoric/camera

**Comment by krishnaff** [comment]
oh great! thanks for the camera package. using it now.
