### ISSUE TITLE
Is it possible to trigger a modal when an input is selected?

### ISSUE THREAD

**Issue by PolGuixe** [meteoric/autoform-ionic#2]
Can we access to the inputs types without using the {{>quickForm ...}}? 
That way I could trigger modals for the inputs e.g a date picker. Is there a way to do this with the {{quickForm...}}?

**Comment by nickw** [comment]
You would want to use `{{#autoForm}}` and [`{{#afFieldInput}}`](https://github.com/aldeed/meteor-autoform#affieldinput), then call `IonModal.open` from a `focus` event handler.

**Comment by PolGuixe** [comment]
Any idea how to transfer the value selected in the modal to the input? 
I was thinking on a session variable but I don't know if there is a better way.

**Comment by nickw** [comment]
Hmm yeah we don't have any callbacks for modals yet, so I think a `Session` variable or a `reactive-var` is probably your best bet.

**Comment by PolGuixe** [comment]
Many thanks. I'll try it this way.
