### ISSUE TITLE
publish ver 0.1.6 to atmosphere

### ISSUE THREAD

**Issue by benstr** [meteoric/autoform-ionic#21]
Currently atmosphere has version 0.1.5 only. Can one of the org owners publish 0.1.6?

**Comment by judsonbsilva** [comment]
I need too, and if is possible update the meteor-autoform version from 5.3 to lastest ( is the 5.5.1 )

**Comment by kevohagan** [comment]
@nickw @gwendall that would be great!

**Comment by avishaan** [comment]
I am in the same boat⛵️

**Comment by AlexFrazer** [comment]
Agreed.

**Comment by myktra** [comment]
Wound up forking this and including as a submodule for now. Since this package has no tests and is already presumably compatible with 5.3, simply upgrading the dependency to autoform 5.7.1 and publishing to Atmosphere at this point is all that is really needed?

**Comment by evanglerm** [comment]
Is this issue resolved ? I am still not able to get Autofor-ionic 0.1.6.

**Comment by logankoester** [comment]
:+1:

**Comment by vhf** [comment]
+1

**Comment by benstr** [comment]
Version 0.16 has been published with a dep to autoform 5.8.1

**Comment by avishaan** [comment]
amazeballs
