### ISSUE TITLE
Checkbox is not working on ionic template.

### ISSUE THREAD

**Issue by felipesmendes** [meteoric/autoform-ionic#4]
I created one field to recieve array of string with this code:

dias: {
    type: [String],
    optional: true,
    autoform: {
      type: "select-checkbox",
      'label-type': 'placeholder',
      placeholder: 'Dias',
      options: function () {
        return [
          {label: "Segunda-Feira", value: 'Segunda-Feira'},
          {label: "Terça-Feira", value: 'Terça-Feira'},
          {label: "Quarta-Feira", value: 'Quarta-Feira'},
          {label: "Quinta-Feira", value: 'Quinta-Feira'},
          {label: "Sexta-Feira", value: 'Sexta-Feira'},
          {label: "Sábado", value: 'Sábado'},
          {label: "Domingo", value: 'Domingo'}
        ];
      }
    }
  },

Then in QuickFOrm the checkbox fields looks like this:

![autoform](https://cloud.githubusercontent.com/assets/992965/6147378/efa355e2-b1dd-11e4-8d81-4b2daa819097.png)

Have some way to fix it or it is a bug?

**Comment by nickw** [comment]
Hmm yeah looks like we haven't implemented `select-checkbox` correctly. I'll see if I can get some time this weekend to take a look at it.

**Comment by aldeed** [comment]
I ran into this, too, and worked around it by adding `label=false` on the `afQuickField`.

**Comment by nickw** [comment]
Fixed in 1.0.5
