### ISSUE TITLE
Multiple select with options

### ISSUE THREAD

**Issue by elGusto** [meteoric/autoform-ionic#6]
The layout in portrait on my android device is not optimal. I would much prefer to have the select's label on top of it instead of on it's right side. Right now, it causes the options' text to be cut if too long.

![screen shot 2015-02-12 at 15 01 13](https://cloud.githubusercontent.com/assets/1734325/6169182/13617c5e-b2cc-11e4-88ca-0a097102c686.png)

**Comment by nickw** [comment]
I think this was fixed in #4 - make sure you have the latest `1.0.5` installed.

**Comment by elGusto** [comment]
That was it thanks!!

I wasn't specifying any version number for the package, isn't meteor getting the latest version in this case ?

Anyway thank you!
